"""Named continuous and discrete symmetry constructors.

All factories return (LieAlgebra, Representation). Discrete groups have the
zero-dimensional Lie algebra and are specified by finite transformation matrices.
"""
import math
import torch
from .algebra import LieAlgebra, orthogonal
from .representation import Representation


def _dimension(n, minimum=1):
    if isinstance(n, bool) or not isinstance(n, int) or n < minimum:
        raise ValueError(f"Dimension/order must be an integer >= {minimum}")


def _from_basis(g):
    """Structure constants for an independent, Frobenius-orthogonal basis."""
    commutators = g[:, None] @ g[None, :] - g[None, :] @ g[:, None]
    norms = g.square().sum((-1, -2))
    c = torch.einsum("abij,kij->abk", commutators, g) / norms
    algebra = LieAlgebra(c)
    return algebra, Representation(algebra, g)


def so(n, *, dtype=torch.float64, device=None):
    """so(n), including so(2), so(3), and so(4); defining n-vector action.

    Basis is E_ij - E_ji for i<j in lexicographic order, as in orthogonal(n).
    """
    _dimension(n, 2)
    return orthogonal(n, dtype=dtype, device=device)


def se(n, *, dtype=torch.float64, device=None):
    """se(n) on homogeneous points [position, 1], directions [vector, 0].

    For n=3 coordinates are (omega_x,omega_y,omega_z,v_x,v_y,v_z), using
    the standard cross-product matrix. For n=2 they are (theta,v_x,v_y),
    with counterclockwise positive theta. Other n use so(n)'s rotation basis.
    The algebra's adjoint acts on twists; its dual acts on wrenches.
    """
    _dimension(n, 2)
    _, rotations = so(n, dtype=dtype, device=device)
    r = rotations.generators
    if n == 2:
        r = -r
    elif n == 3:
        r = torch.stack((-r[2], r[1], -r[0]))
    g = r.new_zeros(r.shape[0] + n, n + 1, n + 1)
    g[:r.shape[0], :n, :n] = r
    for i in range(n):
        g[r.shape[0] + i, i, n] = 1
    return _from_basis(g)


def translations(n, *, dtype=torch.float64, device=None):
    """Abelian R^n translations acting on homogeneous coordinates."""
    _dimension(n)
    g = torch.zeros(n, n + 1, n + 1, dtype=dtype, device=device)
    for i in range(n):
        g[i, i, n] = 1
    return _from_basis(g)


def torus(n, *, dtype=torch.float64, device=None):
    """SO(2)^n acting on n independent [cos(theta), sin(theta)] pairs.

    Coordinates are independent angles in radians; the algebra is abelian.
    This is useful for periodic joint features, but independent angle shifts
    are not automatically symmetries of a robot's dynamics or task.
    """
    _dimension(n)
    g = torch.zeros(n, 2*n, 2*n, dtype=dtype, device=device)
    for i in range(n):
        g[i, 2*i, 2*i+1], g[i, 2*i+1, 2*i] = -1, 1
    return _from_basis(g)


def similarity(n, *, dtype=torch.float64, device=None):
    """sim(n): se(n) coordinates followed by log-scale; positive scales only."""
    _, rigid = se(n, dtype=dtype, device=device)
    dilation = rigid.generators.new_zeros(1, n + 1, n + 1)
    dilation[0, :n, :n] = torch.eye(n, dtype=dtype, device=device)
    return _from_basis(torch.cat((rigid.generators, dilation)))


def symplectic(n, *, dtype=torch.float64, device=None):
    """sp(2n,R), on phase space [q_1,...,q_n,p_1,...,p_n].

    n is the number of canonical coordinate pairs. This is the real noncompact
    symplectic algebra, not compact quaternionic sp(n). J = [[0,I],[-I,0]].
    """
    _dimension(n)
    basis = []
    for i in range(n):
        for j in range(n):
            g = torch.zeros(2*n, 2*n, dtype=dtype, device=device)
            g[i, j], g[n+j, n+i] = 1, -1
            basis.append(g)
    for upper in (True, False):
        for i in range(n):
            for j in range(i, n):
                g = torch.zeros(2*n, 2*n, dtype=dtype, device=device)
                row, col = (0, n) if upper else (n, 0)
                g[row+i, col+j] = g[row+j, col+i] = 1
                basis.append(g)
    return _from_basis(torch.stack(basis))


def _discrete(matrices, symmetry_id):
    algebra = LieAlgebra(matrices.new_empty(0, 0, 0))
    d = matrices.shape[-1]
    return algebra, Representation(algebra, matrices.new_empty(0, d, d),
                                    discrete_generators=matrices, symmetry_id=symmetry_id)


def cyclic(order, *, dtype=torch.float64, device=None):
    """C_order generated by counterclockwise 2*pi/order rotation of the plane."""
    _dimension(order)
    angle = 2 * math.pi / order
    c, s = math.cos(angle), math.sin(angle)
    # Exact identity for C1 avoids a spurious tiny continuous-looking constraint.
    r = torch.eye(2, dtype=dtype, device=device) if order == 1 else torch.tensor([[c, -s], [s, c]], dtype=dtype, device=device)
    if order == 2:
        r = -torch.eye(2, dtype=dtype, device=device)
    return _discrete(r.unsqueeze(0), f"C{order}:planar-r")


def dihedral(order, *, dtype=torch.float64, device=None):
    """D_order of size 2*order: planar rotation r, then reflection s in x axis."""
    _dimension(order, 2)
    _, rotation = cyclic(order, dtype=dtype, device=device)
    reflection = torch.diag(torch.tensor([1., -1.], dtype=dtype, device=device))
    return _discrete(torch.cat((rotation.discrete_generators, reflection.unsqueeze(0))), f"D{order}:r,s")


def symmetric(order, *, dtype=torch.float64, device=None):
    """S_order on order exchangeable slots, generated by adjacent transpositions.

    This acts on the final feature axis. Combine with a trivial representation
    by tensor_product for multiple scalar channels per slot.
    """
    _dimension(order)
    eye = torch.eye(order, dtype=dtype, device=device)
    matrices = []
    for i in range(order - 1):
        perm = list(range(order))
        perm[i], perm[i+1] = perm[i+1], perm[i]
        matrices.append(eye[perm])
    return _discrete(torch.stack(matrices) if matrices else eye.unsqueeze(0), f"S{order}:adjacent-swaps")


def orthogonal_group(n, *, dtype=torch.float64, device=None):
    """Full O(n): so(n) rotations plus reflection of coordinate zero."""
    algebra, vector = so(n, dtype=dtype, device=device)
    reflection = torch.eye(n, dtype=dtype, device=device)
    reflection[0, 0] = -1
    return algebra, Representation(algebra, vector.generators,
        discrete_generators=reflection.unsqueeze(0), symmetry_id=f"O{n}:reflect-0")


def octahedral(*, reflections=False, dtype=torch.float64, device=None):
    """Cube/octahedron symmetries: 24 rotations, or 48 including reflections.

    Ordered generators: +90 degrees about z, +90 degrees about x, optionally
    reflection of coordinate zero. Matrices are exact signed permutations.
    """
    matrices = [[[0,-1,0],[1,0,0],[0,0,1]], [[1,0,0],[0,0,-1],[0,1,0]]]
    if reflections:
        matrices.append([[-1,0,0],[0,1,0],[0,0,1]])
    return _discrete(torch.tensor(matrices, dtype=dtype, device=device),
                     "Oh:z90,x90,reflect-0" if reflections else "O:z90,x90")
